"""Emit INSERT statements for public.walar_points_place from Excel PointsPlace!B4:M83."""

from __future__ import annotations

import os
from pathlib import Path

from openpyxl import load_workbook

DEFAULT_XLSX = Path(__file__).resolve().parents[1] / "local" / "docs" / "walar-spec" / "WALAR 2026-01-01.xlsx"


def main() -> None:
    path = Path(os.environ.get("WALAR_XLSX", str(DEFAULT_XLSX)))
    if not path.is_file():
        raise SystemExit(f"Workbook not found: {path}")

    wb = load_workbook(path, data_only=True, read_only=True)
    ws = wb["PointsPlace"]
    rows: list[tuple[int, int, float]] = []
    for r in range(4, 84):
        place = r - 3
        for c in range(2, 14):
            wal_idx = c - 1
            v = ws.cell(row=r, column=c).value
            p = 0.0 if v is None else float(v)
            rows.append((place, wal_idx, p))
    wb.close()

    print("-- Seed walar_points_place (generated by scripts/generate_walar_points_place_seed_sql.py)")
    batch = 200
    for i in range(0, len(rows), batch):
        chunk = rows[i : i + batch]
        vals = ",\n  ".join(
            f"({pl}, {wi}, {pt if pt == int(pt) else pt})" for pl, wi, pt in chunk
        )
        print(
            f"insert into public.walar_points_place (place, wal_ar_index, points) values\n  {vals}\n  "
            "on conflict (place, wal_ar_index) do update set points = excluded.points;"
        )


if __name__ == "__main__":
    main()
