"""Emit INSERT statements for public.walar_points_cm from Excel PointsCM!C3:L163."""

from __future__ import annotations

import os
from pathlib import Path

from openpyxl import load_workbook

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_XLSX = REPO_ROOT / "local" / "docs" / "walar-spec" / "WALAR 2026-01-01.xlsx"


def main() -> None:
    path = Path(os.environ.get("WALAR_XLSX", str(DEFAULT_XLSX)))
    wb = load_workbook(path, data_only=True, read_only=True)
    ws = wb["PointsCM"]
    rows: list[tuple[int, int, float]] = []
    for r in range(3, 164):
        total_cm = r - 3
        for c in range(3, 13):
            jump_rounds = c - 2
            v = ws.cell(row=r, column=c).value
            p = 0.0 if v is None else float(v)
            rows.append((total_cm, jump_rounds, p))
    wb.close()

    print("-- Seed walar_points_cm (generated by scripts/generate_walar_points_seed_sql.py)")
    batch = 200
    for i in range(0, len(rows), batch):
        chunk = rows[i : i + batch]
        vals = ",\n  ".join(
            f"({tc}, {jr}, {pt if pt == int(pt) else pt})" for tc, jr, pt in chunk
        )
        print(f"insert into public.walar_points_cm (total_cm, jump_rounds, points) values\n  {vals}\n  on conflict (total_cm, jump_rounds) do update set points = excluded.points;")


if __name__ == "__main__":
    main()
