-- Add common ISO 3166-1 alpha-3 codes missing from country_aliases.
-- Covers codes frequently used in parachuting competition spreadsheets.

insert into public.country_aliases (alias, iso2, note) values
  ('AFG', 'AF', 'alpha-3'),
  ('ALB', 'AL', 'alpha-3'),
  ('ALG', 'DZ', 'alpha-3 (FIVB variant)'),
  ('DZA', 'DZ', 'alpha-3'),
  ('ARG', 'AR', 'alpha-3'),
  ('ARM', 'AM', 'alpha-3'),
  ('AUS', 'AU', 'alpha-3'),
  ('AUT', 'AT', 'alpha-3'),
  ('AZE', 'AZ', 'alpha-3'),
  ('BHR', 'BH', 'alpha-3'),
  ('BEL', 'BE', 'alpha-3'),
  ('BLR', 'BY', 'alpha-3'),
  ('BEN', 'BJ', 'alpha-3'),
  ('BOL', 'BO', 'alpha-3'),
  ('BIH', 'BA', 'alpha-3'),
  ('BRA', 'BR', 'alpha-3'),
  ('BGR', 'BG', 'alpha-3'),
  ('KHM', 'KH', 'alpha-3'),
  ('CMR', 'CM', 'alpha-3'),
  ('CAN', 'CA', 'alpha-3'),
  ('CHL', 'CL', 'alpha-3'),
  ('COL', 'CO', 'alpha-3'),
  ('HRV', 'HR', 'alpha-3'),
  ('CRO', 'HR', 'alpha-3 sport variant'),
  ('CZE', 'CZ', 'alpha-3'),
  ('DNK', 'DK', 'alpha-3'),
  ('EGY', 'EG', 'alpha-3'),
  ('EST', 'EE', 'alpha-3'),
  ('FIN', 'FI', 'alpha-3'),
  ('FRA', 'FR', 'alpha-3'),
  ('GEO', 'GE', 'alpha-3'),
  ('DEU', 'DE', 'alpha-3'),
  ('GER', 'DE', 'alpha-3 sport variant'),
  ('GBR', 'GB', 'alpha-3'),
  ('GRE', 'GR', 'alpha-3 sport variant'),
  ('GRC', 'GR', 'alpha-3'),
  ('HUN', 'HU', 'alpha-3'),
  ('IND', 'IN', 'alpha-3'),
  ('IDN', 'ID', 'alpha-3'),
  ('IRN', 'IR', 'alpha-3'),
  ('IRL', 'IE', 'alpha-3'),
  ('ISR', 'IL', 'alpha-3'),
  ('ITA', 'IT', 'alpha-3'),
  ('JPN', 'JP', 'alpha-3'),
  ('JOR', 'JO', 'alpha-3'),
  ('KAZ', 'KZ', 'alpha-3'),
  ('KEN', 'KE', 'alpha-3'),
  ('KWT', 'KW', 'alpha-3'),
  ('KGZ', 'KG', 'alpha-3'),
  ('LAO', 'LA', 'alpha-3'),
  ('LVA', 'LV', 'alpha-3'),
  ('LBN', 'LB', 'alpha-3'),
  ('LTU', 'LT', 'alpha-3'),
  ('LUX', 'LU', 'alpha-3'),
  ('MAS', 'MY', 'alpha-3 sport variant'),
  ('MYS', 'MY', 'alpha-3'),
  ('MDV', 'MV', 'alpha-3'),
  ('MEX', 'MX', 'alpha-3'),
  ('MDA', 'MD', 'alpha-3'),
  ('MGL', 'MN', 'alpha-3 sport variant'),
  ('MNG', 'MN', 'alpha-3'),
  ('MNE', 'ME', 'alpha-3'),
  ('MAR', 'MA', 'alpha-3'),
  ('MOZ', 'MZ', 'alpha-3'),
  ('NAM', 'NA', 'alpha-3'),
  ('NEP', 'NP', 'alpha-3'),
  ('NED', 'NL', 'alpha-3 sport variant'),
  ('NLD', 'NL', 'alpha-3'),
  ('NZL', 'NZ', 'alpha-3'),
  ('MKD', 'MK', 'alpha-3'),
  ('NOR', 'NO', 'alpha-3'),
  ('OMA', 'OM', 'alpha-3 sport variant'),
  ('OMN', 'OM', 'alpha-3'),
  ('PAK', 'PK', 'alpha-3'),
  ('PSE', 'PS', 'alpha-3'),
  ('PAN', 'PA', 'alpha-3'),
  ('PER', 'PE', 'alpha-3'),
  ('PHI', 'PH', 'alpha-3 sport variant'),
  ('PHL', 'PH', 'alpha-3'),
  ('POL', 'PL', 'alpha-3'),
  ('POR', 'PT', 'alpha-3 sport variant'),
  ('PRT', 'PT', 'alpha-3'),
  ('ROU', 'RO', 'alpha-3'),
  ('RUS', 'RU', 'alpha-3'),
  ('SAU', 'SA', 'alpha-3'),
  ('SEN', 'SN', 'alpha-3'),
  ('SRB', 'RS', 'alpha-3'),
  ('SGP', 'SG', 'alpha-3'),
  ('SVK', 'SK', 'alpha-3'),
  ('SVN', 'SI', 'alpha-3'),
  ('SLO', 'SI', 'alpha-3 sport variant'),
  ('ZAF', 'ZA', 'alpha-3'),
  ('KOR', 'KR', 'alpha-3'),
  ('ESP', 'ES', 'alpha-3'),
  ('LKA', 'LK', 'alpha-3'),
  ('SWE', 'SE', 'alpha-3'),
  ('SWZ', 'SZ', 'alpha-3'),
  ('CHE', 'CH', 'alpha-3'),
  ('SUI', 'CH', 'alpha-3 sport variant'),
  ('SYR', 'SY', 'alpha-3'),
  ('TWN', 'TW', 'alpha-3'),
  ('TJK', 'TJ', 'alpha-3'),
  ('THA', 'TH', 'alpha-3'),
  ('TUN', 'TN', 'alpha-3'),
  ('TUR', 'TR', 'alpha-3'),
  ('TKM', 'TM', 'alpha-3'),
  ('UKR', 'UA', 'alpha-3'),
  ('ARE', 'AE', 'alpha-3'),
  ('USA', 'US', 'alpha-3'),
  ('URY', 'UY', 'alpha-3'),
  ('UZB', 'UZ', 'alpha-3'),
  ('VEN', 'VE', 'alpha-3'),
  ('VNM', 'VN', 'alpha-3')
on conflict (alias) do update set
  iso2 = excluded.iso2,
  note = coalesce(excluded.note, public.country_aliases.note);
