-- WALAR Excel parity: PointsPlace matrix, walar_rating (AV) vs rank_points (AW), wal_ar_score = AW + AX.
-- Seed: apply 20260326110401_walar_points_place_seed.sql next (generated by scripts/generate_walar_points_place_seed_sql.py).

-- ---------------------------------------------------------------------------
-- Placement / rank points matrix (Excel PointsPlace!B4:M83)
-- ---------------------------------------------------------------------------
create table if not exists public.walar_points_place (
  place smallint not null check (place >= 1 and place <= 80),
  wal_ar_index smallint not null check (wal_ar_index >= 1 and wal_ar_index <= 12),
  points numeric not null,
  primary key (place, wal_ar_index)
);

comment on table public.walar_points_place is
  'Excel PointsPlace: placement rank points by finish place (row) and WALAR index / Rang Grupa (column 1..12).';

alter table public.walar_points_place enable row level security;

drop policy if exists "walar_points_place_select_public" on public.walar_points_place;
create policy "walar_points_place_select_public"
  on public.walar_points_place for select using (true);

-- ---------------------------------------------------------------------------
-- competition_results: Excel WALARIN place columns + walar_rating (AV)
-- ---------------------------------------------------------------------------
alter table public.competition_results
  add column if not exists walar_rating numeric;

alter table public.competition_results
  add column if not exists place_overall smallint;

alter table public.competition_results
  add column if not exists place_m smallint;

alter table public.competition_results
  add column if not exists place_f smallint;

alter table public.competition_results
  add column if not exists place_j smallint;

alter table public.competition_results
  add column if not exists place_mj smallint;

alter table public.competition_results
  add column if not exists place_fj smallint;

alter table public.competition_results
  add column if not exists place_master smallint;

comment on column public.competition_results.walar_rating is
  'Excel WALARIN column AV: NT/junior/avg/WPC rating (used in organizer sum).';

comment on column public.competition_results.rank_points is
  'Excel WALARIN column AW: placement points from PointsPlace (not AV).';

-- Backfill: previous rank_points stored Excel AV
update public.competition_results
set walar_rating = rank_points
where walar_rating is null and rank_points is not null;

-- Effective place for PointsPlace row index (Excel AW uses AC=Place M; prefer category-specific columns when set)
create or replace function public.walar_effective_place_for_points(
  p_gender text,
  p_age_category text,
  p_place_overall int,
  p_place_m int,
  p_place_f int,
  p_place_j int,
  p_place_mj int,
  p_place_fj int,
  p_place_master int
)
returns int
language sql
immutable
parallel safe
as $$
  select case
    when lower(trim(coalesce(p_age_category, ''))) = 'junior'
         and upper(trim(coalesce(p_gender, ''))) = 'F'
         and p_place_fj is not null then p_place_fj
    when lower(trim(coalesce(p_age_category, ''))) = 'junior'
         and upper(trim(coalesce(p_gender, ''))) = 'M'
         and p_place_mj is not null then p_place_mj
    when lower(trim(coalesce(p_age_category, ''))) = 'junior'
         and p_place_j is not null then p_place_j
    when lower(trim(coalesce(p_age_category, ''))) = 'master'
         and p_place_master is not null then p_place_master
    when upper(trim(coalesce(p_gender, ''))) = 'F'
         and p_place_f is not null then p_place_f
    when p_place_m is not null then p_place_m
    when p_place_overall is not null then p_place_overall
    else null::int
  end;
$$;

create or replace function public.walar_placement_points_lookup(p_place int, p_wal_ar_index int)
returns numeric
language sql
stable
as $$
  select case
    when p_place is null or p_place < 1 or p_place > 80 then 0::numeric
    when p_wal_ar_index is null or p_wal_ar_index < 1 or p_wal_ar_index > 12 then 0::numeric
    else coalesce(
      (select w.points from public.walar_points_place w
       where w.place = p_place and w.wal_ar_index = p_wal_ar_index),
      0::numeric
    )
  end;
$$;

grant execute on function public.walar_effective_place_for_points(text, text, int, int, int, int, int, int, int) to anon, authenticated, service_role;
grant execute on function public.walar_placement_points_lookup(int, int) to anon, authenticated, service_role;

create or replace function public.walar_recalculate_competition_organizer_points(p_competition_id uuid)
returns void
language plpgsql
as $$
declare
  v_finished int;
  v_bulletin_sum int;
  v_sum_rating numeric;
  v_op numeric;
begin
  select c.finished_jump_rounds into v_finished
  from public.competitions c where c.id = p_competition_id;

  select
    coalesce(c.bulletin_male, 0) + coalesce(c.bulletin_female, 0)
    + coalesce(c.bulletin_jm, 0) + coalesce(c.bulletin_jf, 0)
  into v_bulletin_sum
  from public.competitions c where c.id = p_competition_id;

  select coalesce(sum(coalesce(cr.walar_rating, 0)), 0) into v_sum_rating
  from public.competition_results cr
  where cr.competition_id = p_competition_id;

  v_finished := greatest(coalesce(v_finished, 0), 0);
  v_bulletin_sum := greatest(coalesce(v_bulletin_sum, 0), 0);

  v_op := v_bulletin_sum::numeric * coalesce(v_sum_rating, 0) * v_finished::numeric;

  update public.competitions
  set
    wal_ar_organizer_points = v_op,
    wal_ar_tier = public.walar_tier_from_op(v_op),
    updated_at = now()
  where id = p_competition_id;
end;
$$;

create or replace function public.walar_recalculate_competition_result(p_id uuid)
returns void
language plpgsql
as $$
declare
  r public.competition_results%rowtype;
  c_end date;
  a_dob date;
  eff_cat text;
  ath_gender text;
  ath_lic text;
  t numeric;
  jr int;
  a numeric;
  av numeric;
  ax numeric;
  aw numeric;
  ep int;
  wi int;
begin
  select * into r from public.competition_results where id = p_id;
  if not found then
    return;
  end if;

  select c.end_date, ath.date_of_birth, ath.gender, coalesce(ath.fai_licence, '')
  into c_end, a_dob, ath_gender, ath_lic
  from public.competitions c
  join public.athletes ath on ath.id = r.athlete_id
  where c.id = r.competition_id;

  if trim(ath_lic) = '' then
    update public.competition_results
    set
      age_category = coalesce(
        case
          when a_dob is not null and c_end is not null then public.walar_age_category_from_dates(a_dob, c_end)
          else null
        end,
        r.age_category
      ),
      walar_rating = null,
      rank_points = null,
      results_points = null,
      wal_ar_score = null,
      updated_at = now()
    where id = p_id;
    return;
  end if;

  eff_cat := null;
  if a_dob is not null and c_end is not null then
    eff_cat := public.walar_age_category_from_dates(a_dob, c_end);
  end if;
  if eff_cat is null then
    eff_cat := r.age_category;
  end if;

  select jt.total_cm, jt.jump_rounds, jt.avg_cm
  into t, jr, a
  from public.walar_jump_totals(
    r.jump1_cm, r.jump2_cm, r.jump3_cm, r.jump4_cm, r.jump5_cm, r.jump6_cm, r.jump7_cm, r.jump8_cm,
    r.sf_cm, r.f_cm
  ) as jt;

  av := public.walar_rank_points(r.member_national_team, eff_cat, a, r.wpc_medalist);
  ax := public.walar_results_points_lookup(t, jr);

  ep := public.walar_effective_place_for_points(
    ath_gender,
    eff_cat,
    r.place_overall,
    r.place_m,
    r.place_f,
    r.place_j,
    r.place_mj,
    r.place_fj,
    r.place_master
  );

  select wr.sort_order into wi
  from public.competitions c
  left join public.walar_competition_rang wr on wr.code = c.competition_rang_code
  where c.id = r.competition_id;

  aw := public.walar_placement_points_lookup(ep, wi);

  update public.competition_results
  set
    age_category = eff_cat,
    walar_rating = av,
    rank_points = aw,
    results_points = ax,
    wal_ar_score = aw + ax,
    updated_at = now()
  where id = p_id;
end;
$$;
